// app/src/App.tsx
import React, { useEffect } from "react";
import { SettingsProvider } from "./context/settings";
import { ApiProvider, useApi } from "./context/wasm-api";

import init, { start } from "../public/pkg/eukolia.js";

import styles from "./App.module.scss";
import Toolbar from "./panels/Toolbar";
import Layers from "./panels/Layers";
import { useApp, AppProvider } from "./context/app-state";
import { WidgetsProvider, useWidgets } from "./context/widgets";
import { UiGlobalState, Widget } from "./types";

function App(): React.ReactElement {
  return (
    <>
      <ApiProvider>
        <SettingsProvider>
          <AppProvider>
            <WidgetsProvider>
              <Main />
            </WidgetsProvider>
          </AppProvider>
        </SettingsProvider>
      </ApiProvider>
      <div id="wasm" className={styles.wasm} />
    </>
  );
}

function Main() {
  const [, dispatchApi] = useApi();
  const [, dispatchAppState] = useApp();
  const [, dispatchWidgets] = useWidgets();

  useEffect(() => {
    window.update_app_state = function (app_state: UiGlobalState, widgets: Widget[]) {
      dispatchWidgets({ type: "update", payload: widgets });
      dispatchAppState({ type: "update", payload: app_state });
    };

    // Load WASM
    (async function () {
      await init("/pkg/eukolia_bg.wasm");
      const [
        activate_events,
        add_widget,
        update_widget,
        select_widget,
        hover_widget,
        toggle_visibility_widget,
        delete_widget,
        swap_widget,
        update_settings,
      ] = start();

      dispatchApi({
        type: "update",
        payload: {
          activate_events,
          add_widget,
          update_widget,
          select_widget,
          hover_widget,
          toggle_visibility_widget,
          delete_widget,
          swap_widget,
          update_settings,
        },
      });
    })();
  }, []);

  return (
    <>
      <Toolbar />
      <Layers />
    </>
  );
}

export default App;

// app/src/App.vue
<template>
  <Toolbar />
  <Layers />
  <Panel />
  <div id="wasm" />
</template>

<script lang="ts">
import init, { start } from "/pkg/eukolia.js";
import { State, MUTATE_WIDGET, MUTATE_API, MUTATE_APP_STATE } from "./store";
import { useStore } from "vuex";
import Panel from "./components/Panel.vue";
import Toolbar from "./components/Toolbar.vue";
import Layers from "./components/Layers.vue";

export default {
  components: {
    Panel,
    Toolbar,
    Layers,
  },
  mounted() {
    const store = useStore<State>();

    // TODO deprecate
    (window as any).update_widget_panel = function updateWidgetPanel(payload: any) {
      // console.log("update_widget_panel", payload);
      store.commit(MUTATE_WIDGET, payload);
    };

    (window as any).update_app_state = function updateAppState(app_state, widgets) {
      // console.log("update", payload);
      store.commit(MUTATE_APP_STATE, { app_state, widgets });
    };

    // Load WASM
    (async function () {
      await init("/pkg/eukolia_bg.wasm");
      const [
        activate_events,
        add_widget,
        update_widget,
        select_widget,
        hover_widget,
        toggle_visibility_widget,
        delete_widget,
      ] = start();

      store.commit(MUTATE_API, {
        activate_events,
        add_widget,
        update_widget,
        select_widget,
        hover_widget,
        toggle_visibility_widget,
        delete_widget,
      });
    })();
  },
};
</script>

<style>
#wasm canvas {
  display: block;
  position: fixed;
  top: 0;
  left: 0;
  cursor: none;
}
</style>
