// app/src/components/Layers.vue
<template>
  <div class="left-panel" v-if="showUi">
    <div class="layer-tools">
      <div class="layer-tool" @click="onLayerMove(-2)">
        <i class="fad fa-bring-front fa-sm" />
      </div>
      <div class="layer-tool" @click="onLayerMove(-1)">
        <i class="fad fa-bring-forward fa-sm" />
      </div>
      <div class="layer-tool" @click="onLayerMove(1)">
        <i class="fad fa-send-backward fa-sm" />
      </div>
      <div class="layer-tool" @click="onLayerMove(2)">
        <i class="fad fa-send-back fa-sm" />
      </div>
    </div>
    <div class="layers" @click="onDeselect" @mouseover="onHover(null)">
      <div class="not-found" v-if="searchFor && widgets.length === 0">
        No layers with "{{ searchFor }}" found.
      </div>
      <div
        class="layer"
        v-for="widget in widgets"
        :key="widget.uuid"
        :class="{
          selected: widget.uuid === active_widget_uuid,
          hovered: widget.uuid === pointer_widget_uuid,
          hidden: !widget.visible,
          edit: editMode === widget.uuid,
        }"
        @click.stop="onClick(widget.uuid)"
        @mouseover.stop="onHover(widget.uuid)"
      >
        <div class="layer--name">
          <i class="layer-icon fad fa-vector-square fa-xs" />
          <div v-if="editMode === widget.uuid" class="edit">
            <input
              :value="widget.name"
              @blur="onExit"
              @change="(e) => onRename(e, widget)"
              @keydown="(e) => onLayeyKeyDown(e)"
              :id="`layer-${widget.uuid}`"
            />
          </div>
          <div v-else @dblclick="onEditLayerName(widget.uuid)" class="name">
            {{ widget.name || "&nbsp;" }}
          </div>
        </div>
        <div class="tool" @click.stop="onHide(widget.uuid)">
          <i class="fad fa-eye-slash fa-xs" />
        </div>
      </div>
    </div>
    <div class="search" :class="{ active: searchFor }">
      <i class="fad fa-search fa-sm" />
      <input
        type="text"
        @blur="onExit"
        @change="onExit"
        @focus="onEnter"
        v-model="searchFor"
        placeholder="Search Layers"
      />
      <div class="clear-search" @click="onClearSearch" v-if="searchFor">
        <i class="fad fa-times-circle fa-sm" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { reactive, toRefs, computed, nextTick, ComputedRef } from "vue";
import { useStore } from "vuex";
import Fuse from "fuse.js";
import { State, Widget } from "../store";

interface InnerState {
  editMode: string | null;
  searchFor: string;
  active_widget_uuid: ComputedRef<string | undefined | null>;
  pointer_widget_uuid: ComputedRef<string | undefined | null>;
  widgets: ComputedRef<Widget[]>;
  showUi: ComputedRef<boolean>;
}

export default {
  setup() {
    const store = useStore<State>();
    const state = reactive<InnerState>({
      editMode: null,
      searchFor: "",
      active_widget_uuid: computed(() => store.state.app?.active_widget_uuid),
      pointer_widget_uuid: computed(() => store.state.app?.pointer_widget_uuid),
      widgets: computed(() => {
        const widgets = store.state.app?.widgets ?? [];
        const fuse = new Fuse(widgets, { keys: ["name"] });
        return widgets?.filter((widget) => {
          if (!fuse || state.searchFor.trim() === "") return true;
          return fuse
            .search(state.searchFor)
            .map((r) => r.item.uuid)
            .includes(widget.uuid);
        });
      }),
      showUi: computed(() => !store.state.localSettings.hideUserInterface),
    });

    function onClick(uuid: string) {
      store.state.api.select_widget(uuid);
    }

    function onHover(uuid: string | null) {
      store.state.api.hover_widget(uuid);
    }

    function onEditLayerName(uuid: string) {
      onEnter();
      state.editMode = uuid;
      nextTick(() => {
        const inputElement = <HTMLInputElement | null>document.getElementById(`layer-${uuid}`);
        if (inputElement) {
          // inputElement.focus();
          inputElement.select();
        }
      });
    }

    function onEnter() {
      store.state.api.activate_events(false);
    }

    function onExit() {
      store.state.api.activate_events(true);
      state.editMode = null;
    }

    function onDeselect() {
      store.state.api.select_widget(null);
    }

    function onHide(uuid: string) {
      store.state.api.toggle_visibility_widget(uuid);
    }

    function onRename(event: Event, widget: Widget) {
      const name = (<HTMLInputElement>event.target)?.value;
      store.state.api.update_widget({
        ...widget,
        name,
      });
      onExit();
    }

    function onLayeyKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        onExit();
      }
    }

    function onClearSearch() {
      state.searchFor = "";
    }

    function onLayerSwap(uuid: string, a: number, b: number) {
      store.state.api.swap_widget({ uuid, a, b });
    }

    function onLayerMove(direction: number) {
      const len = state.widgets.length;
      let goTo = false;
      for (let i = 0; i < len; i += 1) {
        const widget = state.widgets[i];
        if (widget.uuid === store.state.app?.active_widget_uuid) {
          goTo = !goTo;
        }

        if (goTo) {
          if (Math.abs(direction) === 1) {
            // up, down: single swap
            onLayerSwap(widget.uuid, i, i + direction);
            // don't swap next
            goTo = direction > 0;
          } else if (direction > 0) {
            // bottom: swap all next
            onLayerSwap(widget.uuid, i, i + 1);
            // don't swap next
            goTo = false;
          } else {
            // top
            // swap all previous
            for (let y = i; y > 0; y -= 1) {
              onLayerSwap(widget.uuid, y, y - 1);
            }
            // don't swap next
            goTo = false;
          }
        }
      }
    }

    return {
      ...toRefs(state),
      onClick,
      onHover,
      onEditLayerName,
      onDeselect,
      onHide,
      onRename,
      onExit,
      onLayeyKeyDown,
      onEnter,
      onClearSearch,
      onLayerMove,
    };
  },
};
</script>

<style scoped>
.left-panel {
  position: absolute;
  top: 68px;
  left: 10px;
  width: 240px;
  max-height: calc(100vh - 78px);
  background: var(--grey-panel);
  z-index: 9;
  border: 2px solid var(--primary-ink);
  border-radius: 5px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  border: 0;
  box-shadow: 0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108);
  background: rgba(255, 255, 255, 0.8);
  -webkit-backdrop-filter: blur(40px);
  backdrop-filter: blur(40px);
}

.layers {
  overflow-y: auto;
  user-select: none;
  display: flex;
  flex-direction: column;
  /*gap: 1px;*/
  padding: 10px 3px;
  flex: 1;
}

.layer:not(:last-child) {
  margin-bottom: 1px;
}

.layer {
  display: flex;
  padding: 4px 8px;
  border-radius: 4px;
  cursor: default;
  justify-content: space-between;
  align-items: center;
}

/*.layer:hover:not(.selected),*/
.hovered:not(.selected) {
  box-shadow: inset 0 0 0 2px var(--widget-blue);
}

.selected {
  background: var(--widget-pink);
  color: white;
}

.layer--name {
  display: flex;
  align-items: center;
  flex: 1;
  overflow: hidden;
}

.layer-icon {
  margin-right: 4px;
}

.name {
  min-width: 50px;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
  flex: 1;
  font-size: 12px;
}

.tool {
  display: none;
}

.selected .tool {
  color: white;
}

.layer.hidden:not(.edit) .tool,
.layer:hover:not(.edit) .tool {
  display: flex;
}

.edit,
input {
  width: 100%;
  line-height: 0;
}

input {
  font-size: 12px;
  background: white;
  border-radius: 2px;
  padding: 2px 4px;
  outline: 0;
  line-height: 1;
}

.search {
  display: flex;
  padding: 8px 4px;
  align-items: center;
  color: var(--secondary-grey);
}

.search.active {
  color: var(--teal-70);
}

.search input {
  background: transparent;
  color: var(--teal-70);
}

.search input::placeholder {
  color: var(--secondary-grey);
  opacity: 0.5;
}

.search .clear-search,
.search .fa-search {
  margin: 0 4px;
  line-height: 1;
}

.layer-tools {
  display: flex;
  padding: 8px 6px;
  justify-content: flex-end;
}

.layer-tool {
  line-height: 1;
}

.layer-tool:focus,
.layer-tool:hover {
  outline: 0;
  color: var(--blue-50);
}

.layer-tool:not(:last-child) {
  margin-right: 8px;
}

.not-found {
  text-align: center;
  padding: 10px;
  word-break: break-word;
  font-size: 12px;
  color: var(--teal-70);
}
</style>

// app/src/panels/Layers.tsx
import React, { useContext, useEffect, useRef, useState } from "react";
import style from "./Layers.module.scss";
import { useSettings } from "../context/settings";
import { useWidgets } from "../context/widgets";
import type { Widget } from "../types";
import cx from "clsx";
import { useApp } from "../context/app-state";
import Fuse from "fuse.js";
import { useApi } from "../context/wasm-api";
import { useFocus, useHover, useKeyboard, usePress } from "@react-aria/interactions";
import { FocusRing, useFocusRing } from "@react-aria/focus";
import type { AriaButtonProps } from "@react-types/button";
import { useButton } from "@react-aria/button";

type ReactState<T> = [T, React.Dispatch<React.SetStateAction<T>>];

// eslint-disable-next-line @typescript-eslint/no-empty-function
const SearchContext = React.createContext<ReactState<string>>(["", () => {}]);

export default function Layers(): JSX.Element {
    const searchState = useState<string>("");

    return (
        <SearchContext.Provider value={searchState}>
            <LayersPanel />
        </SearchContext.Provider>
    );
}

// --- Layers Panel ---
function LayersPanel(): JSX.Element | null {
    const [settings] = useSettings();
    let [widgets] = useWidgets();
    const [search] = useContext(SearchContext);

    if (search) {
        const fuse = new Fuse(widgets, { keys: ["name"] });
        widgets = widgets?.filter((widget) => {
            if (!fuse || search.trim() === "") return true;
            return fuse
                .search(search)
                .map((r) => r.item.uuid)
                .includes(widget.uuid);
        });
    }

    if (settings.hideUserInterface || !widgets || (!widgets.length && !search)) {
        return null;
    }

    return (
        <div className={style.panel}>
            <Tools />
            <div className={style.layers}>
                {widgets.map((widget) => (
                    <Layer key={widget.uuid} widget={widget} />
                ))}
                {search && widgets.length === 0 && (
                    <div className={style.notFound}>No layers with &quot;{search}&quot; found.</div>
                )}
            </div>
            <Search />
        </div>
    );
}

// --- Tools ---
export function Tools(): JSX.Element {
    const [api] = useApi();
    const [app] = useApp();
    const [widgets] = useWidgets();

    function onLayerSwap(uuid: string, a: number, b: number) {
        api.swap_widget({ uuid, a, b });
    }

    function onLayerMove(direction: number) {
        const len = widgets.length;
        let goTo = false;
        // FIXME: Avoid loop | Recode properly
        // Extract from and add to the beginning/end
        for (let i = 0; i < len; i += 1) {
            const widget = widgets[i];
            if (widget.uuid === app?.active_widget_uuid) {
                goTo = !goTo;
            }

            if (goTo) {
                if (Math.abs(direction) === 1) {
                    // up, down: single swap
                    onLayerSwap(widget.uuid, i, i + direction);
                    // don't swap next
                    // goTo = direction > 0;
                    goTo = false;
                } else if (direction > 0) {
                    // bottom: swap all next
                    onLayerSwap(widget.uuid, i, i + 1);
                    // don't swap next
                    goTo = false;
                } else {
                    // top
                    // swap all previous
                    for (let y = i; y > 0; y -= 1) {
                        onLayerSwap(widget.uuid, y, y - 1);
                    }
                    // don't swap next
                    goTo = false;
                }
            }
        }
    }

    return (
        <div className={style.layerTools}>
            <Tool iconClassName={"fa-bring-front"} onPress={() => onLayerMove(-2)} />
            <Tool iconClassName={"fa-bring-forward"} onPress={() => onLayerMove(-1)} />
            <Tool iconClassName={"fa-send-backward"} onPress={() => onLayerMove(1)} />
            <Tool iconClassName={"fa-send-back"} onPress={() => onLayerMove(2)} />
        </div>
    );
}

type ToolProps = {
    iconClassName: string;
};

function Tool(props: AriaButtonProps & ToolProps): JSX.Element {
    const ref = useRef<HTMLButtonElement>(null);
    const { buttonProps } = useButton(props, ref);
    const { focusProps, isFocusVisible } = useFocusRing();
    const { hoverProps, isHovered } = useHover({});

    return (
        <button
            className={cx(style.layerTool, style.icon, { focus: isFocusVisible, hover: isHovered })}
            ref={ref}
            {...buttonProps}
            {...focusProps}
            {...hoverProps}
        >
            <i className={cx("fad", "fa-md", props.iconClassName)} />
        </button>
    );
}

// --- Layer ---
type LayerProps = { widget: Widget };

function Layer({ widget }: LayerProps): JSX.Element | null {
    const [app] = useApp();
    const [api] = useApi();
    const ref = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLInputElement>(null);
    const [editMode, setEditMode] = useState<boolean>(false);
    const [name, setName] = useState<string>(widget.name);
    const { hoverProps } = useHover({
        onHoverChange: (isHovering) => {
            if (isHovering) api.hover_widget(widget.uuid);
            else api.hover_widget(null);
        },
    });
    const { focusProps } = useFocus({
        onFocus: () => api.select_widget(widget.uuid),
    });
    const { pressProps } = usePress({
        onPress: () => {
            api.toggle_visibility_widget(widget.uuid);
        },
    });

    useEffect(() => {
        if (widget.uuid === app?.active_widget_uuid) {
            ref.current?.focus();
        } else {
            setEditMode(false);
        }
    }, [app?.active_widget_uuid]);

    useEffect(() => {
        if (editMode) {
            inputRef.current?.select();
            api.activate_events(false);
        } else {
            // FIXME: Fucking fails twice and after it's ok...
            try {
                api.activate_events(true);
            } catch {
                /* empty */
            }
        }
    }, [editMode]);

    if (!app) {
        return null;
    }

    function updateName(event: React.KeyboardEvent<HTMLInputElement>) {
        if (event.key === "Escape") {
            setName(widget.name);
            setEditMode(false);
        } else if (event.key === "Enter") {
            api.update_widget({
                ...widget,
                name,
            });
            setEditMode(false);
        }
    }

    return (
        <div
            className={cx(style.layer, {
                [style.selected]: widget.uuid === app.active_widget_uuid,
                [style.hovered]: widget.uuid === app.pointer_widget_uuid,
                [style.hidden]: !widget.visible,
                [style.edit]: editMode,
            })}
            {...hoverProps}
            {...focusProps}
            tabIndex={0}
            role="button"
            ref={ref}
        >
            <div className={style.layerName}>
                <i className={cx(style.layerIcon, "fad", "fa-vector-square", "fa-sm")} />
                {editMode ? (
                    <div className={style.edit}>
                        <input
                            value={name}
                            ref={inputRef}
                            onChange={(event) => setName(event.currentTarget.value)}
                            onKeyDown={updateName}
                        />
                    </div>
                ) : (
                    <div className={style.name} onDoubleClick={() => setEditMode(true)}>
                        {widget.name || " "}
                    </div>
                )}
            </div>
            <div className={style.tool} {...pressProps}>
                <i className="fad fa-eye-slash fa-sm" />
            </div>
        </div>
    );
}

// --- Search ---
function Search() {
    const [search, setSearch] = useContext(SearchContext);
    const [api] = useApi();
    const ref = useRef<HTMLInputElement>(null);
    const { focusProps } = useFocus({
        onFocus: () => api.activate_events(false),
        onBlur: () => api.activate_events(true),
    });
    const { keyboardProps } = useKeyboard({
        onKeyDown: (e) => {
            if (e.key === "Escape") setSearch("");
        },
    });
    const { pressProps } = usePress({
        onPress: () => {
            setSearch("");
            ref.current?.focus();
        },
    });

    return (
        <div className={cx(style.search, { [style.active]: search })}>
            <i className={cx("fad fa-search fa-md", style.icon)} aria-hidden="true" />
            <input
                type="text"
                placeholder="Search Layers"
                value={search}
                ref={ref}
                onChange={(event) => setSearch(event.target.value)}
                {...focusProps}
                {...keyboardProps}
            />
            {search && (
                <FocusRing focusRingClass={style.clearFocus}>
                    <button className={cx(style.clearSearch, style.icon)} {...pressProps}>
                        <i className="fad fa-times-circle fa-sm" />
                    </button>
                </FocusRing>
            )}
        </div>
    );
}
