// app/src/components/Toolbar.vue
<template>
  <div class="container">
    <div class="group">
      <div class="toolbar">
        <div class="title">Eukolia <span class="tag">beta</span></div>
        <button class="button" @click="addWidget('smiley')">
          <i class="fad fa-smile-plus fa-lg" />
        </button>
      </div>
    </div>
    <div class="group">
      <div class="toolbar" v-if="showUi">
        <a class="button" href="https://docs.eukolia.design" target="_blank">
          <i class="fad fa-book fa-lg" />
        </a>
        <a
          class="button"
          :href="'https://twitter.com/intent/tweet\\?text=Hi%20@EukoliaDesign,'"
          target="_blank"
        >
          <i class="fad fa-comment-alt-smile fa-lg" />
        </a>
      </div>
      <div class="toolbar" :class="{ hide: !showUi }">
        <button class="button" @click="toggleUi">
          <i class="fad fa-window-frame-open fa-lg" v-if="showUi" />
          <i class="fad fa-window-frame fa-lg" v-else />
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { toRefs } from "vue";
import { useStore } from "vuex";
import { State, TOGGLE_UI } from "../store";
import { reactive, computed } from "vue";

export default {
  setup() {
    const store = useStore<State>();
    const state = reactive({
      showUi: computed(() => !store.state.localSettings.hideUserInterface),
    });

    function addWidget(widget: string) {
      // TODO dispatch action?
      store.state.api.add_widget(widget);
    }

    function toggleUi() {
      store.dispatch(TOGGLE_UI);
    }

    return { ...toRefs(state), addWidget, toggleUi };
  },
};
</script>

<style scoped>
.container {
  display: flex;
  justify-content: space-between;
  position: absolute;
  top: 10px;
  left: 10px;
  width: calc(100vw - 20px);
}

.group {
  display: flex;
}

.toolbar {
  /*border-bottom: 1px solid #a7a7a7;*/
  /*box-shadow: inset 0 -1px 0 0 #bdbdbd, inset 0 1px 0 0 #f5f5f5;*/
  align-items: center;
  background: var(--grey-panel);
  display: flex;
  height: 48px;
  padding: 0 12px;
  /* min-width: 250px; */
  z-index: 9;
  border: 0;
  background: rgba(255, 255, 255, 0.8);
  -webkit-backdrop-filter: blur(10px);
  backdrop-filter: blur(10px);
  border-radius: 5px;
  box-shadow: 0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108);
}

.toolbar:not(:last-child) {
  margin-right: 5px;
}

.toolbar.invert {
  background: var(--primary-ink);
  color: white;
}

.toolbar.hide {
  background: var(--blue-50);
}

.title {
  font-weight: bold;
  margin-right: 10px;
}

.tag {
  background: var(--orange-50);
  border-radius: 8px;
  bottom: 8px;
  color: white;
  display: inline-block;
  font-size: 10px;
  font-weight: normal;
  padding: 1px 6px;
  position: relative;
  right: 6px;
}

.button {
  border-radius: 4px;
  display: flex;
  /* font-size: 16px; */
  padding: 4px 6px;
  transition: 300ms;
}

.button:not(:last-child) {
  margin-right: 5px;
}

.button:focus,
.button:hover {
  outline: 0;
  color: var(--blue-50);
}

.toolbar.hide .button {
  color: white !important;
}
</style>

// app/src/panels/Toolbar.tsx
import React from "react";
import cx from "clsx";
import { useSettings } from "../context/settings";
import { useApi } from "../context/wasm-api";
import style from "./Toolbar.module.scss";
import ToolbarButton from "../widgets/ToolbarButton";
import ToolbarLink from "../widgets/ToolbarLink";

export default function Toolbar(): JSX.Element {
    const [settings, dispatchSettings] = useSettings();
    const [{ add_widget }] = useApi();
    const showUI = !settings.hideUserInterface;

    return (
        <div className={style.container}>
            <div className={style.group}>
                <div className={style.toolbar}>
                    <div className={style.title}>
                        Fluss <span className={style.tag}>beta</span>
                    </div>
                    {add_widget && (
                        <ToolbarButton onPress={() => add_widget("smiley")}>
                            <i className="fad fa-smile-plus fa-lg" />
                        </ToolbarButton>
                    )}
                </div>
                <div className={style.toolbar} hidden>
                    <button className={style.button}>
                        <i className="fad fa-undo fa-lg" />
                    </button>
                    <button className={style.button}>
                        <i className="fad fa-redo fa-lg" />
                    </button>
                </div>
                <div className={style.toolbar} hidden>
                    <div className={style.button}>
                        <i className="fad fa-spinner-third fa-spin fa-lg" />
                    </div>
                    {showUI && <span>My_Design_File.eukolia</span>}
                </div>
            </div>
            <div className={style.group}>
                {showUI && (
                    <div className={style.toolbar} hidden>
                        <div className={style.button}>
                            <i className="fad fa-user-secret fa-lg" />
                        </div>
                        <div className={style.button}>
                            <i className="fad fa-user-injured fa-lg" />
                        </div>
                        <div className={style.button}>
                            <i className="fad fa-user-alien fa-lg" />
                        </div>
                        <div className={style.button}>
                            <i className="fad fa-user-astronaut fa-lg" />
                        </div>
                    </div>
                )}
                {showUI && (
                    <div className={style.toolbar} hidden>
                        <div className={style.button} hidden>
                            <i className="fad fa-sliders-v fa-lg" />
                        </div>
                        <ToolbarLink
                            href="https://docs.eukolia.design"
                            target="_blank"
                            rel="noreferrer"
                        >
                            <i className="fad fa-book fa-lg" />
                        </ToolbarLink>
                        <ToolbarLink
                            href="https://twitter.com/intent/tweet\?text=Hi%20@EukoliaDesign"
                            target="_blank"
                            rel="noreferrer"
                        >
                            <i className="fad fa-comment-alt-smile fa-lg" />
                        </ToolbarLink>
                    </div>
                )}
                <div className={cx(style.toolbar, { [style.invert]: !showUI })}>
                    <ToolbarButton onPress={() => dispatchSettings({ type: "toggleUi" })}>
                        {showUI ? (
                            <i className="fad fa-window-frame-open fa-lg" />
                        ) : (
                            <i className="fad fa-window-frame fa-lg" />
                        )}
                    </ToolbarButton>
                </div>
            </div>
        </div>
    );
}

// TODO import widgets
